spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:anz;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # OAuth2 Resource server
  security:
    oauth2:
      resource:
        token-info-uri: http://localhost:8080/oauth/check_token

# OAuth2 Authorisation server
security:
  oauth2:
    client:
      client-id: anz-example
      client-secret: its-a-secret